In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries Loaded Successfully!")

Libraries Loaded Successfully!

In [2]:
nav = pd.read_csv(
    r"C:\Users\UDAY KIRAN\Desktop\mutual fund analytics\Data\processed\02_nav_history_clean.csv"
)

nav.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [3]:
nav = nav.sort_values(
    ["amfi_code","date"]
)

nav["daily_return"] = (
    nav.groupby("amfi_code")["nav"]
       .pct_change()
)

nav.head()

   amfi_code        date       nav  daily_return
0     100016  2022-01-03  520.4608           NaN
1     100016  2022-01-04  515.0971     -0.010306
2     100016  2022-01-05  521.7239      0.012865
3     100016  2022-01-06  515.7880     -0.011377
4     100016  2022-01-07  515.1639     -0.001210

In [4]:
nav["daily_return"].describe()

count    45960.000000
mean         0.000631
std          0.010290
min         -0.058102
25%         -0.005042
50%          0.000340
75%          0.006324
max          0.064713
Name: daily_return, dtype: float64

In [5]:
nav.head()

   amfi_code        date       nav  daily_return
0     100016  2022-01-03  520.4608           NaN
1     100016  2022-01-04  515.0971     -0.010306
2     100016  2022-01-05  521.7239      0.012865
3     100016  2022-01-06  515.7880     -0.011377
4     100016  2022-01-07  515.1639     -0.001210

In [6]:
var_cvar_results = []

for code in nav["amfi_code"].unique():

    fund = nav[
        nav["amfi_code"] == code
    ]

    returns = fund["daily_return"].dropna()

    if len(returns) > 30:

        var_95 = returns.quantile(0.05)

        cvar_95 = returns[
            returns <= var_95
        ].mean()

        var_cvar_results.append(
            [
                code,
                var_95,
                cvar_95
            ]
        )

var_cvar_df = pd.DataFrame(
    var_cvar_results,
    columns=[
        "amfi_code",
        "VaR_95",
        "CVaR_95"
    ]
)

var_cvar_df.head()

   amfi_code    VaR_95   CVaR_95
0     100016 -0.014364 -0.018060
1     100025 -0.003793 -0.004994
2     100033 -0.019034 -0.023456
3     101206 -0.013282 -0.017439
4     101207 -0.026021 -0.032459

In [7]:
var_cvar_df.to_csv(
    r"C:\Users\UDAY KIRAN\Desktop\mutual fund analytics\outputs\var_cvar_report.csv",
    index=False
)

print("VaR/CVaR Report Saved!")

VaR/CVaR Report Saved!

In [8]:
var_cvar_df.sort_values(
    "VaR_95"
).head(10)

    amfi_code    VaR_95   CVaR_95
22     119599 -0.026859 -0.032384
17     119095 -0.026188 -0.031667
4      101207 -0.026021 -0.032459
11     118634 -0.025438 -0.032304
21     119598 -0.024507 -0.030595
39     149324 -0.023483 -0.031036
7      102886 -0.019220 -0.023251
2      100033 -0.019034 -0.023456
25     120505 -0.018892 -0.024342
16     119094 -0.018480 -0.024260

In [9]:
var_cvar_df.head()

   amfi_code    VaR_95   CVaR_95
0     100016 -0.014364 -0.018060
1     100025 -0.003793 -0.004994
2     100033 -0.019034 -0.023456
3     101206 -0.013282 -0.017439
4     101207 -0.026021 -0.032459

In [10]:
var_cvar_df.sort_values(
    "VaR_95"
).head()

    amfi_code    VaR_95   CVaR_95
22     119599 -0.026859 -0.032384
17     119095 -0.026188 -0.031667
4      101207 -0.026021 -0.032459
11     118634 -0.025438 -0.032304
21     119598 -0.024507 -0.030595

In [11]:
top5_codes = [
    120505,
    148567,
    120843,
    100033,
    148569
]

In [12]:
top5_codes = [
    120505,
    148567,
    120843,
    100033,
    148569
]

In [13]:
sharpe_df.sort_values(
    "sharpe_ratio",
    ascending=False
).head()

NameError: name 'sharpe_df' is not defined

In [14]:
top5_codes = [
    120505,
    148567,
    120843,
    100033,
    148569
]

In [15]:
transactions = pd.read_csv(
    r"C:\Users\UDAY KIRAN\Desktop\mutual fund analytics\Data\processed\08_investor_transactions_clean.csv"
)

transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [16]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

In [17]:
first_txn = (
    transactions.groupby("investor_id")
    ["transaction_date"]
    .min()
)

transactions["cohort_year"] = (
    transactions["investor_id"]
    .map(first_txn.dt.year)
)

transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,cohort_year
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,2024
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,2024
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,2024
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,2024
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,2024

In [18]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,cohort_year
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,2024
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,2024
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,2024
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,2024
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,2024

In [19]:
cohort_summary = (
    transactions.groupby("cohort_year")
    .agg(
        avg_sip_amount=("amount_inr","mean"),
        total_invested=("amount_inr","sum")
    )
    .reset_index()
)

cohort_summary

   cohort_year  avg_sip_amount  total_invested
0         2024   107422.541832      3491125187
1         2025   109158.577061        30455243

In [20]:
top_fund = (
    transactions.groupby(
        ["cohort_year","amfi_code"]
    )
    .size()
    .reset_index(name="count")
)

top_fund = top_fund.sort_values(
    ["cohort_year","count"],
    ascending=[True,False]
)

top_fund.groupby("cohort_year").head(1)

    cohort_year  amfi_code  count
35         2024     148568    874
62         2025     119599     12

In [21]:
sip_only = transactions[
    transactions["transaction_type"] == "SIP"
].copy()

sip_only = (
    sip_only.groupby("investor_id")
    .filter(lambda x: len(x) >= 6)
)

In [22]:
sip_only = sip_only.sort_values(
    ["investor_id","transaction_date"]
)

sip_only["gap_days"] = (
    sip_only.groupby("investor_id")
    ["transaction_date"]
    .diff()
    .dt.days
)

In [23]:
gap_summary = (
    sip_only.groupby("investor_id")
    ["gap_days"]
    .mean()
    .reset_index()
)

gap_summary.head()

  investor_id   gap_days
0   INV000004  85.400000
1   INV000008  70.400000
2   INV000010  64.800000
3   INV000011  40.166667
4   INV000012  57.000000

In [24]:
gap_summary["status"] = np.where(
    gap_summary["gap_days"] > 35,
    "At Risk",
    "Healthy"
)

gap_summary.head()

  investor_id   gap_days   status
0   INV000004  85.400000  At Risk
1   INV000008  70.400000  At Risk
2   INV000010  64.800000  At Risk
3   INV000011  40.166667  At Risk
4   INV000012  57.000000  At Risk

In [25]:
gap_summary["status"].value_counts()

status
At Risk    1332
Healthy      30
Name: count, dtype: int64

In [26]:
cohort_summary

   cohort_year  avg_sip_amount  total_invested
0         2024   107422.541832      3491125187
1         2025   109158.577061        30455243

In [27]:
gap_summary["status"].value_counts()

status
At Risk    1332
Healthy      30
Name: count, dtype: int64

In [28]:
total = len(gap_summary)

healthy_pct = (
    (gap_summary["status"]=="Healthy")
    .sum()
    / total
) * 100

risk_pct = (
    (gap_summary["status"]=="At Risk")
    .sum()
    / total
) * 100

print("Healthy:", round(healthy_pct,2), "%")
print("At Risk:", round(risk_pct,2), "%")

Healthy: 2.2 %
At Risk: 97.8 %

In [29]:
portfolio = pd.read_csv(
    r"C:\Users\UDAY KIRAN\Desktop\mutual fund analytics\Data\processed\09_portfolio_holdings_clean.csv"
)

portfolio.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [30]:
portfolio.columns

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')

In [31]:
portfolio["weight_sq"] = (
    portfolio["weight_pct"] / 100
) ** 2

In [32]:
hhi_df = (
    portfolio.groupby("amfi_code")
    ["weight_sq"]
    .sum()
    .reset_index()
)

hhi_df.head()

   amfi_code  weight_sq
0     100016   0.139534
1     100033   0.147592
2     101206   0.129332
3     101207   0.200700
4     102885   0.174709

In [33]:
hhi_df["concentration"] = np.where(
    hhi_df["weight_sq"] > 0.25,
    "Highly Concentrated",
    np.where(
        hhi_df["weight_sq"] > 0.15,
        "Moderately Concentrated",
        "Diversified"
    )
)

hhi_df.head()

   amfi_code  weight_sq            concentration
0     100016   0.139534              Diversified
1     100033   0.147592              Diversified
2     101206   0.129332              Diversified
3     101207   0.200700  Moderately Concentrated
4     102885   0.174709  Moderately Concentrated

In [34]:
hhi_df.sort_values(
    "weight_sq",
    ascending=False
).head(10)

    amfi_code  weight_sq            concentration
11     119092   0.206448  Moderately Concentrated
3      101207   0.200700  Moderately Concentrated
18     119599   0.174751  Moderately Concentrated
4      102885   0.174709  Moderately Concentrated
7      118632   0.168298  Moderately Concentrated
29     148568   0.167930  Moderately Concentrated
21     120505   0.157570  Moderately Concentrated
22     120506   0.153794  Moderately Concentrated
27     125498   0.152414  Moderately Concentrated
23     120841   0.149680              Diversified

In [35]:
hhi_df.to_csv(
    r"C:\Users\UDAY KIRAN\Desktop\mutual fund analytics\outputs\sector_hhi_report.csv",
    index=False
)

print("Sector HHI Report Saved!")

Sector HHI Report Saved!